name: Github CI - Development

on:
  push:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      docker:
        image: docker:dind
        env:
          DOCKER_HOST: "tcp://docker:2375"
          DOCKER_DRIVER: overlay2
          DOCKER_TLS_CERTDIR: ""
        ports:
          - 2375:2375
        options: --privileged --tls=false -v /var/run/docker.sock:/var/run/docker.sock


    steps:
      - name: 📁 Check out the repository
        uses: actions/checkout@v3

      - name: 🏗 Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: 🔨 Build the project
        run: gradle build -x test --stacktrace
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧪 Run tests
        run: gradle test --stacktrace
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}