name: Github CI - Development

on:
  push:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read


    steps:
      - name: 📁 Check out the repository
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker-in-Docker
        uses: addnab/docker-run-action@v3
        with:
          image: docker:dind
          options: --privileged --name docker -it -d --rm --privileged -e DOCKER_TLS_CERTDIR="" -e DOCKER_HOST="tcp://docker:2375" -e DOCKER_DRIVER=overlay2 -e DOCKER_TLS_VERIFY=0 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp -v /var/lib/docker:/var/lib/docker -p 2375:2375

      - name: 🏗 Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: 🐳 Check Docker version
        run: docker version

      - name: 🐳 Check running containers
        run: docker ps

      - name: 🐳 Check Docker-in-Docker version
        run: docker exec docker docker version

      - name: 🔨 Build the project
        run: gradle build -x test --stacktrace
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧪 Run tests
        run: gradle test --stacktrace
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}