name: Github CI - Production

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with Gradle
        run: gradle build aggregateJavadoc
        env:
          RELEASE_TYPE: "releases"

          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.YGG_TOKEN }}

      - name: Upload doc artifacts
        uses: actions/upload-artifact@v3
        with:
          name: YggTools-Doc
          path: build/docs/aggregateJavadoc


  doc:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Download doc artifacts
        uses: actions/download-artifact@v3
        with:
          name: YggTools-Doc
          path: YggTools-Doc/

      - name: Publish doc to Github Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.YGG_TOKEN }}
          publish_dir: ./YggTools-Doc/

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Publish to Maven Repository
        run: gradle publish
        env:
          RELEASE_TYPE: "releases"

          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.YGG_TOKEN }}

          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
