name: Github CI

on:
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with Gradle
        run: gradle build
        env:
          RELEASE_TYPE: ${{ github.ref_name }}

          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: YggTools
          path: |
            Redis/build/libs/
            Tools/build/libs/

      - name: Upload doc artifacts
        uses: actions/upload-artifact@v3
        with:
          name: YggTools-Doc
          path: |
            Redis/build/docs/
            Tools/build/docs/

  doc:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Download doc artifacts
        uses: actions/download-artifact@v3
        with:
          name: YggTools-Doc

      - name: Create doc archive
        run: |
          mkdir YggDoc
          cp -r YggTools-Doc/Tools/build/docs/javadoc YggDoc/
          cp -r YggTools-Doc/Redis/build/docs/javadoc YggDoc/Redis

      - name: Upload doc archive
        uses: actions/upload-artifact@v3
        with:
          name: YggTools-Doc-Deploy
          path: YggDoc/

  deploy-doc:
    needs: doc
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Download doc artifacts
        uses: actions/download-artifact@v3
        with:
          name: YggTools-Doc-Deploy

      - name: Publish doc to Github Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          personal_token: ${{ secrets.YGG_TOKEN }}
          publish_dir: ./YggTools-Doc-Deploy/YggDoc/

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: YggTools

      - name: Move build artifacts to target folder
        run: |
          cp -r YggTools/Redis Redis/
          cp -r YggTools/Tools Tools/

      - name: Publish to Maven Repository
        run: gradle publish
        env:
          RELEASE_TYPE: ${{ github.ref_name }}

          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
