name: Publish CI

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with Gradle
        run: gradle build

      - name: Publish to Maven Repository
        run: gradle publish
        env:
          RELEASE_TYPE: ${{ github.ref_name }}

          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}